
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 13
#define YY_END_OF_BUFFER 14
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[103] =
    {   0,
        0,    0,   14,   12,    2,    1,   12,   12,   12,   10,
       12,   11,   12,    7,    7,    9,    8,    9,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
        2,    9,    0,    0,    4,    0,    0,    6,    0,    7,
        7,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    5,    0,    3,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    1,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,    1,    1,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   26,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       27,   28,   29,   30,    1,    1,   31,   32,   33,   34,

       35,   25,   36,   37,   38,   25,   39,   40,   41,   42,
       43,   44,   25,   45,   46,   47,   48,   49,   50,   25,
       51,   25,   52,    1,   53,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[54] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    1,    1,    1,    1,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    1,    1
    } ;

static const flex_int16_t yy_base[107] =
    {   0,
        0,    0,  172,  173,  169,  173,  147,  161,    0,  173,
      163,  173,   37,  173,   42,  144,  143,  142,   45,  124,
      125,  113,  119,   27,  129,  111,   47,  123,   31,  120,
      154,  173,    0,  150,    0,  146,  145,   50,   56,   62,
       66,  105,  115,  119,  103,  103,  104,  107,  104,  107,
       45,  103,  111,   50,  100,   95,  134,  173,  103,  173,
       97,   89,   99,   90,   98,  100,   96,   90,   94,   93,
       87,   82,   81,   92,   80,   77,   73,   85,   84,   83,
       72,   85,   82,   74,   70,   62,   69,   79,   77,   62,
       59,   56,   61,   66,   49,   58,   44,   55,   50,   38,

       51,  173,   94,   66,   99,  104
    } ;

static const flex_int16_t yy_def[107] =
    {   0,
      102,    1,  102,  102,  102,  102,  102,  103,  104,  102,
      105,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  106,  102,  104,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  106,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,

      102,    0,  102,  102,  102,  102
    } ;

static const flex_int16_t yy_nxt[227] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   12,
       10,   10,   12,   10,   13,   10,   14,   15,   15,   12,
       12,   16,   17,   18,    4,   19,   12,   10,   12,   10,
       20,   21,    4,    4,   22,    4,    4,   23,    4,   24,
       25,   26,   27,    4,   28,   29,   30,    4,    4,    4,
        4,   12,   12,   38,   38,   38,   39,   46,   40,   40,
       40,   41,   41,   41,   41,   52,   38,   38,   38,   47,
       35,   53,   38,   38,   38,   68,   39,   54,   40,   40,
       40,   55,   41,   41,   72,   60,  101,  100,   69,   60,
       99,   60,   73,   50,   33,   98,   97,   33,   33,   36,

       60,   36,   60,   36,   57,   60,   60,   96,   57,   95,
       94,   60,   93,   60,   92,   91,   60,   90,   60,   89,
       88,   87,   86,   85,   60,   60,   84,   83,   82,   60,
       81,   80,   60,   60,   79,   78,   77,   76,   58,   75,
       74,   71,   70,   67,   66,   65,   64,   63,   62,   61,
       60,   59,   58,   58,   58,   31,   56,   51,   49,   48,
       45,   44,   43,   42,   32,   32,   32,   37,   34,   32,
       31,  102,    3,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,

      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102
    } ;

static const flex_int16_t yy_chk[227] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   13,   13,   13,   15,   24,   15,   15,
       15,   19,   19,   27,   27,   29,   38,   38,   38,   24,
      104,   29,   39,   39,   39,   51,   40,   29,   40,   40,
       40,   29,   41,   41,   54,  101,  100,   99,   51,   98,
       97,   96,   54,   27,  103,   95,   94,  103,  103,  105,

       93,  105,   92,  105,  106,   91,   90,   89,  106,   88,
       87,   86,   85,   84,   83,   82,   81,   80,   79,   78,
       77,   76,   75,   74,   73,   72,   71,   70,   69,   68,
       67,   66,   65,   64,   63,   62,   61,   59,   57,   56,
       55,   53,   52,   50,   49,   48,   47,   46,   45,   44,
       43,   42,   37,   36,   34,   31,   30,   28,   26,   25,
       23,   22,   21,   20,   18,   17,   16,   11,    8,    7,
        5,    3,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,

      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "analizador.l"
#line 2 "analizador.l"
    /*
    Analizador léxico-sintáctico para lenguaje definido en clase
    Compiladores 2023-1
    Autor: Angel Alvarado Campos
    Profesor: M.C. Laura Sandoval Montaño
    Fecha de entrega: 8 de diciembre

    Objetivo: Construir en un mismo programa, los analizadores léxico y sintáctico descendente
    recursivo que revisen programas escritos en el lenguaje definido por la gramática del Anexo A
    del documento de requisitos para este programa.

    Descripción: Se trata de un programa que implementa a las fases de análisis léxico
    y sintáctica de un compilador para un lenguaje definido en clase. Este analizador
    reconoce las 9 clases de componentes léxicos, distingue errores léxicos y sintácticos,
    e indica si un programa es correcto o no. También tiene como salidas a diferentes archivos
    de texto con información util sobre el proceso de compilación.
    */
   
    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>

    //################## ESTRUCTURAS DE DATOS ###########################
    /*
        Definición de las estructuras de datos para las tablas de literales
        Lista ligada para tablas de literales (Clases 3 y 4)
    */
    typedef struct nodo_lit {
        int pos;    // Posicion
        char* dato; // Dato
        struct nodo_lit* next;
    } nodo_lit;

    /*
        Definición de estructura de datos para tabla de símbolos
        Lista ligada para tabla de símbolos (Clase 1)
        No permite duplicados
    */
    typedef struct nodo_tabsim {
        int pos;    // Posición
        char* nombre_id;    // Nombre del identificador
        int tipo;   // Tipo de dato: Inicial es -1 
        struct nodo_tabsim* next;
    } nodo_tabsim;

    /*
        Definición de estructura de datos para la cadena de atomos. Es en esencia
        una lista ligada que no verifica si hay elementos duplicados. El dato que se
        almacena en cada nodo es un caracter que representa al átomo.
    */
    typedef struct nodo_atomo {
        char atomo;     // Valor del átomo
        struct nodo_atomo* next;    // Átomo siguiente
    } nodo_atomo;

    //################## PROTOTIPOS DE FUNCIONES ###########################
    int insertar_simbolo(nodo_tabsim**,char*);
    int buscar_simbolo(nodo_tabsim*, char*);
    int print_tabsim(nodo_tabsim*);
    int insertar_literal(nodo_lit**,char*,int);
    int print_tablit(nodo_lit*);
    int valor_palRes(char*);
    int valor_opRela(char*);
    char atomo_opRela(char*);
    char atomo_palRes(char*);
    int insertar_atomo(nodo_atomo**,char);

    //################## INICIALIZACIONES ###########################
    // Inicialización de tablas de literales
    int num_Reales = -1;
    int num_Constantes = -1;
    nodo_lit* head_Real = NULL; // Tabla de literales de constantes reales (clase 3)
    nodo_lit* head_Cadenas = NULL;  // Tabla de literales de constantes cadenas (clase 4)

    // Inicializacion de tabla de símbolos
    int num_identificadores = -1;
    nodo_tabsim* head_tabsim = NULL;    // Tabla de símbolos (clase 1) 

    int num_atomos = 0; // Inicia a contar átomos desde 0: 0 significa, 0 átomos en cadena
    nodo_atomo* head_atomos = NULL; // Inicializa cadena de átomos, se va llenando en la ejecución

    char* cadena_atomos = NULL; // Cadena de átomos final, es entrada del analizador sintáctico

    int linea = 0; // Contador de saltos de linea
    int errores_lexicos = 0;    // Contador de errores léxicos
    int errores_sintacticos = 0;    // Contador de errores sintácticos

    // Archivos
    FILE* LiteralesReales;
    FILE* LiteralesCadenas;
    FILE* Simbolos;
    FILE* Tokens;
    FILE* Errores;
    FILE* Atomos;
    
    //################## DEFINICION DE FUNCIONES ###########################
    /*
        Función que permite realizar la inserción de un identificador en la tabla
        de símbolos. No permite la inserción de valores duplicados.
        Tiene como valor de retorno a un entero que denota la posición en la que
        el identificador fue insertado en la lista, en un rango de posiciones de
        [0, size - 1].
        Si el identificador argumentado ya se encuentra en la lista, entonces se tendrá
        como valor de retorno a la posición del identificador en la tabla de símbolos.
    */
    int insertar_simbolo (nodo_tabsim** head, char* identificador){
        if (buscar_simbolo(*head,identificador) >= 0){
            return buscar_simbolo(*head,identificador);
        } else {
            // Insertar
            num_identificadores++;
            int posicion = num_identificadores;
            nodo_tabsim* nodo_nuevo = (nodo_tabsim*) malloc(sizeof(nodo_tabsim));
            nodo_nuevo -> nombre_id = strdup(identificador);
            nodo_nuevo -> tipo = -1; // Inicial es -1: Se modificará en futuras entregas
            nodo_nuevo -> pos = posicion;
            nodo_nuevo -> next = NULL;
            if (*head == NULL){
                *head = nodo_nuevo;
            } else {
                nodo_tabsim* nodo_aux = *head;
                while (nodo_aux -> next != NULL){
                    nodo_aux = nodo_aux -> next; 
                }
                nodo_aux -> next = nodo_nuevo;
            }
            return nodo_nuevo -> pos;
        }
    }

    /*
        Función auxiliar, permite imprimir el contenido de la tabla de símbolos
    */
    int print_tabsim(nodo_tabsim* head){
        nodo_tabsim* current = head;
        while (current != NULL){
            printf("[%s]", current->nombre_id);
            current = current -> next;
        }
        return 0;
    }

    /*
        Función auxiliar de la función de insertar_simbolo. Se encarga de realizar la búsqueda
        de un identificador argumentado en la tabla de símbolos para identificar si es posible
        realizar la inserción, debido a que no se permiten duplicados en la tabla de símbolos.
        Si el identificador ya se encuentra en la tabla de simbolos, entonces se retorna la
        posición del identificador en la tabla.
        Por otro lado, si el identificador no se encuentra en la tabla se retorna un -1, para
        distinguir que el identificador no se encuentra en una posición de la tabla de simbolos.
    */
    int buscar_simbolo(nodo_tabsim* head, char* identificador){
        nodo_tabsim* current = head;
        while (current != NULL){
            if (strcmp(current -> nombre_id, identificador) == 0){
                // Retorna la posición del identificador en la tab. de simbolos
                return current -> pos;
            }
            current = current -> next;
        }
        // Retorna posición invalida, indicando que no se encuentra en la tabla
        return -1;
    }

    /*
        Permite obtener el valor correspondiente a cada
        palabra reservada (clase 0), según el catalogo
        descrito en los requerimientos del programa.
    */
    int valor_palRes(char* palabra){
        if (strcmp(palabra, "alternative") == 0){
            return 0;
        } else if (strcmp(palabra, "big") == 0) {
            return 1;
        } else if (strcmp(palabra, "evaluate") == 0) {
            return 2;
        } else if (strcmp(palabra, "instead") == 0) {
            return 3;
        } else if (strcmp(palabra, "large") == 0) {
            return 4;
        } else if (strcmp(palabra, "loop") == 0) {
            return 5;
        } else if (strcmp(palabra, "make") == 0) {
            return 6;
        } else if (strcmp(palabra, "number") == 0) {
            return 7;
        } else if (strcmp(palabra, "other") == 0) {
            return 8;
        } else if (strcmp(palabra, "real") == 0) {
            return 9;
        } else if (strcmp(palabra, "repeat") == 0) {
            return 10;
        } else if (strcmp(palabra, "select") == 0) {
            return 11;
        } else if (strcmp(palabra, "small") == 0) {
            return 12;
        } else if (strcmp(palabra, "step") == 0) {
            return 13;
        } else if (strcmp(palabra, "stop") == 0) {
            return 14;
        } else if (strcmp(palabra, "symbol") == 0) {
            return 15;
        } else {   
            // if palabra es "throw"
            return 16;
        }
    }

    /*
        Función que permite obtener el valor entero del
        operador relacional (clase 7), según lo descrito en el
        catalogo de operadores relacionales descrito
        en los requerimientos del programa.
    */
    int valor_opRela(char* operador){
        if (strcmp(operador, "<") == 0){
            return 0;
        } else if (strcmp(operador, ">") == 0){
            return 1;
        } else if (strcmp(operador, "<=") == 0){
            return 2;
        } else if (strcmp(operador, ">=") == 0){
            return 3;
        } else if (strcmp(operador, "==") == 0){
            return 4;
        } else {
            // if operador es "!="
            return 5;
        }
    }

    /*
        Permite insertar nuevos valores en las tablas de literales
        No verifica si hay duplicados para realizar la inserción, por lo cual se aceptan duplicados.
        Tiene como valor de retorno a la posición del nuevo valor en la tabla.
        Es usada para la tabla de literales de enteros (clase 1), reales (clase 2) y cadenas (clase 3)
    */
    int insertar_literal (nodo_lit** head, char* valor, int clase){
        int posicion = -1;
        if (clase == 3){ // Clase 3: Reales
            num_Reales++;
            posicion = num_Reales;
        } else if (clase == 4){ // Clase 4: Cadenas
            num_Constantes++;
            posicion = num_Constantes;
        }

        if (posicion != -1){    // Si es clase 3 o 4
            nodo_lit* nuevoNodo = (nodo_lit*) malloc(sizeof(nodo_lit));
            nuevoNodo -> dato = strdup(valor);
            nuevoNodo -> next = NULL;
            nuevoNodo -> pos = posicion;
            if (*head == NULL){
                *head = nuevoNodo;
            } else {
                nodo_lit* nodoAux = *head;
                while (nodoAux -> next != NULL){
                    nodoAux = nodoAux -> next;
                }
                nodoAux -> next = nuevoNodo;
            }
            return nuevoNodo -> pos;    // Retorna posición de la inserción actual
        }
        return -1;
    }

    /*
        Función auxiliar, permite imprimir el contenido de las tablas de literales
    */
    int print_tablit(nodo_lit* head){
        nodo_lit* current = head;
        while (current != NULL){
            printf("[%s]", current->dato);
            current = current -> next;
        }
        return 0;
    }

    /*
        Función que permite escribir el contenido de una tabla de literales 
        (de constantes numéricas reales o constantes cadenas) descrita por un nodo
        de tipo nodo_lit en un archivo argumentado de tipo FILE*.
    */
    int write_tablit(FILE* archivo, nodo_lit* head){
        nodo_lit* current = head;
        int posicion = 0;
        while (current != NULL){  
            fprintf(archivo, "%d\t%s\n", posicion, current->dato);
            current = current -> next;
            posicion++;
        }
        return 0;
    }

    /*
        Función que permite escribir el contenido de una tabla de simbolos
        descrita por un nodo de tipo nodo_tabsim en un archivo argumentado de tipo FILE*.
    */
    int write_tabsim(FILE* archivo, nodo_tabsim* head){
        nodo_tabsim* current = head;
        int posicion = 0;
        while (current != NULL){
            fprintf(archivo, "%d\t%s\t%d\n", posicion, current->nombre_id, -1);
            current = current -> next;
            posicion++;
        }
        return 0;
    }

    /*
        Función que permite leer el contenido de un archivo argumentado de tipo FILE*
        desde la terminal.
    */
    int read_file(FILE* archivo){
        char c_aux;
        fread(&c_aux,sizeof(char),1,archivo);
        while(feof(archivo) == 0){
            printf("%c",c_aux);
            fread(&c_aux,sizeof(char),1,archivo);
        }
        printf("\n\n");
        return 0;
    }

    /*
        Función para obtener un átomo para los operadores
        relacionales
    */
    char atomo_opRela(char* operador){
        if (strcmp(operador, "<") == 0){
            return '<';
        } else if (strcmp(operador, ">") == 0){
            return '>';
        } else if (strcmp(operador, "<=") == 0){
            return 'l';
        } else if (strcmp(operador, ">=") == 0){
            return 'u';
        } else if (strcmp(operador, "==") == 0){
            return 'e';
        } else {
            // if operador es "!="
            return 'd';
        }
    }

    /*
        Función para obtener un átomo para las palabras
        reservadas
    */
    char atomo_palRes(char* palabra){
        if (strcmp(palabra, "alternative") == 0){
            return 'a';
        } else if (strcmp(palabra, "big") == 0) {
            return 'b';
        } else if (strcmp(palabra, "evaluate") == 0) {
            return 'f';
        } else if (strcmp(palabra, "instead") == 0) {
            return 't';
        } else if (strcmp(palabra, "large") == 0) {
            return 'g';
        } else if (strcmp(palabra, "loop") == 0) {
            return 'w';
        } else if (strcmp(palabra, "make") == 0) {
            return 'm';
        } else if (strcmp(palabra, "number") == 0) {
            return '#';
        } else if (strcmp(palabra, "other") == 0) {
            return 'o';
        } else if (strcmp(palabra, "real") == 0) {
            return 'x';
        } else if (strcmp(palabra, "repeat") == 0) {
            return 'j';
        } else if (strcmp(palabra, "select") == 0) {
            return 'h';
        } else if (strcmp(palabra, "small") == 0) {
            return 'p';
        } else if (strcmp(palabra, "step") == 0) {
            return 'c';
        } else if (strcmp(palabra, "stop") == 0) {
            return 'q';
        } else if (strcmp(palabra, "symbol") == 0) {
            return 'y';
        } else {   
            // if palabra es "throw"
            return 'z';
        }
    }

    /*
        Función de inserción de átomos en la estructura de datos nodo_atomo.
    */
    int insertar_atomo(nodo_atomo** head, char valor){
        nodo_atomo* nuevo_atomo = (nodo_atomo*) malloc(sizeof(nodo_atomo));
        nuevo_atomo -> atomo = valor;
        nuevo_atomo -> next = NULL;
        if (*head == NULL){
            *head = nuevo_atomo;
        } else {
            nodo_atomo* nodoAux = *head;
            while (nodoAux -> next != NULL){
                nodoAux = nodoAux -> next;
            }
            nodoAux -> next = nuevo_atomo;
        }
        num_atomos++;
        return 0;
    }

    /*
        Función que permite, una vez llenada la estructura de datos nodo_atomo, convertir al contenido
        de esta estructura de datos en una cadena de caracteres. Tiene como tipo de retorno un apuntador a
        un arreglo de caracteres que representa a la cadena de átomos.
    */
    char* generar_cadena_atomos(nodo_atomo* head){
        char* cadena_atomos = malloc(sizeof(char) * (num_atomos+1));
        nodo_atomo* current = head;
        int i = 0;
        while (current != NULL){
            cadena_atomos[i] = current -> atomo; 
            current = current -> next;
            i++;
        }
        return cadena_atomos;
    }
#line 952 "lex.yy.c"
#line 953 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 443 "analizador.l"

#line 1172 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 103 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 173 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 444 "analizador.l"
{
    // Cuenta saltos de línea
    //printf("Salto de linea en linea: %d\n", linea);
    linea++;
    }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 449 "analizador.l"
{
    // Omite espacios entre los componentes
    //printf("Espacio en linea: %d\n", linea);
    ;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 454 "analizador.l"
{
    // CLASE 0
    fprintf(Tokens, "(0\t%d)\n", valor_palRes(yytext)); // Token clase 0
    insertar_atomo(&head_atomos, atomo_palRes(yytext)); // Se inserta el átomo, correspondiente a la palabra reservada
    fprintf(Atomos, "%d\t%c\n", num_atomos-1, atomo_palRes(yytext));    // Se añade el átomo al archivo txt de cadena de átomos
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 460 "analizador.l"
{
    // CLASE 1
    fprintf(Tokens, "(1\t%d)\n", insertar_simbolo(&head_tabsim, yytext)); // Token clase 1
    insertar_atomo(&head_atomos, 'i');  // Se inserta el átomo i (identificador) a la cadena de átomos
    fprintf(Atomos, "%d\t%c\n", num_atomos-1, 'i'); // Se añade el átomo al archivo de texto de cadena de átomos
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 466 "analizador.l"
{
    // CLASE 4
    fprintf(Tokens, "(4\t%d)\n", insertar_literal(&head_Cadenas, yytext, 4)); // Token clase 4
    insertar_atomo(&head_atomos, 's');  // Se añade el átomo s (cadenas) a la cadena de átomos
    fprintf(Atomos, "%d\t%c\n", num_atomos-1, 's'); // Se añade el átomo al archivo de texto de cadena de átomos
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 472 "analizador.l"
{
    // CLASE 3
    // Prioridad sobre las enteras
    fprintf(Tokens, "(3\t%d)\n", insertar_literal(&head_Real, yytext, 3)); // Token clase 3
    insertar_atomo(&head_atomos, 'r');  // Se añade el átomo r (números reales) a la cadena de átomos
    fprintf(Atomos, "%d\t%c\n", num_atomos-1, 'r'); // Se añade el átomo al archivo de texto de cadena de átomos
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 479 "analizador.l"
{
    // CLASE 2
    fprintf(Tokens, "(2\t%s)\n", yytext); // Token clase 2
    insertar_atomo(&head_atomos, 'n');  // Se añade el átomo n (números enteros) a la cadena de átomos
    fprintf(Atomos, "%d\t%c\n", num_atomos-1, 'n'); // Se añade el átomo al archivo de texto de cadena de átomos
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 485 "analizador.l"
{
    // CLASE 8
    // Prioridad sobre los operadores relacionales
    fprintf(Tokens, "(8\t=)\n");    // Token clase 8
    insertar_atomo(&head_atomos, '=');  // Se añade el átomo =, de operador de asignación, a la cadena de átomos
    fprintf(Atomos, "%d\t%c\n", num_atomos-1, '='); // Se añade el átomo al archivo de texto de cadena de átomos
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 492 "analizador.l"
{
    // CLASE 7
    fprintf(Tokens,"(7\t%d)\n", valor_opRela(yytext));  // Token clase 7
    insertar_atomo(&head_atomos, atomo_opRela(yytext)); // Se añade el átomo correspondiente a la operación relacional
    fprintf(Atomos, "%d\t%c\n", num_atomos-1, atomo_opRela(yytext));    // Se añade el átomo al archivo de cadena de átomos
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 498 "analizador.l"
{
    // CLASE 6
    fprintf(Tokens, "(6\t%s)\n", yytext);   // Token clase 6
    insertar_atomo(&head_atomos, *yytext);  // Se añade un átomo, idéntico a la operación aritmética, a la cadena de átomos
    fprintf(Atomos, "%d\t%s\n", num_atomos-1, yytext);  // Se añade el átomo al archivo de cadena de átomos
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 504 "analizador.l"
{
    // CLASE 5
    fprintf(Tokens, "(5\t%s)\n", yytext); // Token clase 5
    insertar_atomo(&head_atomos, *yytext);  // Se añade el átomo, idéntico al símbolo especial, a la cadena de átomos
    fprintf(Atomos, "%d\t%s\n", num_atomos-1, yytext);  // Se añade el átomo al archivo de cadena de átomos
} 
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 510 "analizador.l"
{
    fprintf(Errores, "ERROR LÉXICO: %s en linea %d\n", yytext, linea);
    errores_lexicos++; // Incremento en conteo de errores léxicos
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 514 "analizador.l"
ECHO;
	YY_BREAK
#line 1353 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 103 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 103 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 102);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 514 "analizador.l"


//################## PROTOTIPOS DE FUNCIONES RECURSIVAS ###########################
/*
    Las funciones que se enlistan como prototipos en las siguientes lineas fueron definidas
    en función de los conjuntos de selección de las producciones propuestas en la gramática
    del lenguaje.
*/
int PROGRAM();
int OTRAFUNC();
int FUNC();
int PARAM();
int OTROPARAM();
int CUERPO();
int DECL();
int D();
int TIPO();
int K();
int Q();
int N();
int B();
int C();
int A();
int APRIMA();
int E();
int EPRIMA();
int T();
int TPRIMA();
int F();
int R();
int RPRIMA();
int V();
int VPRIMA();
int VPRIMA2();
int VPRIMA3();
int P();
int LISTAP();
int W();
int I();
int IPRIMA();
int J();
int Y();
int X();
int Z();
int H();
int CPRIMA();
int OPRIMA();
int U();
int DEVUELVE();
int VALOR();
int LLAMA();
int ARG();
int OTROARG();

// Prototipos de funciones útiles en el análisis sintáctico recursivo
char get_char();
int rechaza(char*);

// Variables globales útiles en el análisis sintáctico
int index_cadena = -1; // Indica el índice actual, que refiere al caracter c en revisión, de la cadena de átomos
char c; // Variable global que indica al caracter-átomo en curso

/*
    Función getchar para analizar a la cadena de átomos en la etapa de análisis
    sintáctico recursivo.
    Cada vez que se realiza una llamada se manda al caracter en curso de la cadena de átomos.
*/
char get_char(){
    index_cadena++; 
    char cc = cadena_atomos[index_cadena];
    //printf("CARACTER ACTUAL DE LA CADENA DE ÁTOMOS: %c\n",cc); 
    return cc;
}

/*
    Función de rechazo de cadena. Es una función que recibe como argumento a una cadena de caracteres que debe representar
    a los átomos que se esperaban cuando se presentó el rechazo. Es una función genérica presente en varias situaciones de rechazo
    Cada vez que se hace una llamada a la función, se realiza un incremento unitario en la variable global de errores sintácticos.
*/
int rechaza(char* sim_esperados){
    fprintf(Errores, "ERROR SINTÁCTICO: Átomo %c en índice %d, se esperaba %s\n", c, index_cadena, sim_esperados);
    errores_sintacticos++;
    return 0;
}

//########################### DEFINICIÓN DE LAS FUNCIONES RECURSIVAS ###################################
int PROGRAM(){
    if (c == 'b' || c == 'g' || c == '#' || c == 'y' || c == 'x'){ // prod 1, caso 4
        FUNC();
        OTRAFUNC();
        return 0;
    } else {
        // rechaza;
        rechaza("b g # y x");
        return 0;
    }
}

int OTRAFUNC(){
    if (c == 'b' || c == 'g' || c == '#' || c == 'y' || c == 'x'){ // prod 2, caso 4
        FUNC();
        OTRAFUNC();
        return 0;
    } else if (c == '\0') { // prod 3, caso 3  FIN DE CADENA
        //printf("Se encontró un fin de cadena en átomo: %d", index_cadena);
        return 0;
    } else {
        // rechaza
        rechaza("b g # y x \\0");
        return 0;
    }
}

int FUNC(){
    if (c == 'b' || c == 'g' || c == '#' || c == 'y' || c == 'x') { // PROD 4, CASO 4
        TIPO();
        if (c == 'i'){
            c = get_char();
        } else {
            // rechaza
            rechaza("i");
        }
        if (c == '('){
            c = get_char();
        } else {
            // rechaza
            rechaza("(");
        }
        PARAM();
        if (c == ')'){
            c = get_char();
        } else {
            // rechaza
            rechaza(")");
        }
        if (c == '{'){
            c = get_char();
        } else {
            // rechaza
            rechaza("{");
        }
        CUERPO();
        if (c == '}'){
            c = get_char();
        } else {
            // rechaza
            rechaza("}");
        }
        return 0;
    } else {
        // rechaza
        rechaza("b g # y x");
        return 0;
    }
}

int PARAM(){
    if (c == 'b' || c == 'g' || c == '#' || c == 'y' || c == 'x') { // prod 5, caso 4
        TIPO();
        if (c == 'i'){
            c = get_char();
        } else {
            rechaza("i");
            // rechaza
        }
        OTROPARAM();
        return 0;
    } else if (c == ')'){   // prod 6, caso 3
        return 0;
    } else {
        // rechaza
        rechaza("b g # y x )");
        return 0;
    }
}

int OTROPARAM(){
    if (c == ','){  // prod 7, caso 2
        c = get_char();
        TIPO();
        if (c == 'i'){
            c = get_char();
        } else {
            // rechaza;
            rechaza("i");
        }
        OTROPARAM();
        return 0;
    } else if (c == ')'){   // prod 8, caso 3
        return 0;
    } else {
        // rechaza
        rechaza(", )");
        return 0;
    }
}

int CUERPO(){
    if (c=='b'||c=='g'||c=='#'||c=='y'||c=='x'||c=='c'||c=='i'||c=='f'||c=='h'||c=='w'||c=='j'||c=='['||c=='z'||c=='}'){    // prod 9, caso 3
        DECL();
        LISTAP();
        return 0;
    } else {
        rechaza("b g # y x c i f h w j [ z }");
        // rechaza
        return 0;
    }
}

int DECL(){
    if (c=='c'||c=='i'||c=='f'||c=='h'||c=='w'||c=='j'||c=='['||c=='z'||c=='}'){
        return 0;
    } else if (c=='b'||c=='g'||c=='#'||c=='y'||c=='x'){
        D();
        DECL();
        return 0;
    } else {
        // rechaza
        rechaza("c i f h w j [ z } b g # y x");
        return 0;
    }
}

int D(){
    if (c=='b'||c=='g'||c=='#'||c=='y'||c=='x'){
        TIPO();
        K();
        if (c==';'){
            c=get_char();
        }else{
            //rechaza
            rechaza(";");
        }
        return 0;
    }else{
        rechaza("b g # y x");
        //rechaza
        return 0;
    }
}

int TIPO(){
    if (c=='b'){
        c=get_char();
        return 0;
    } else if (c=='g'){
        c=get_char();
        return 0;
    } else if (c=='#'){
        c=get_char();
        return 0;
    } else if (c=='y'){
        c=get_char();
        return 0;
    } else if (c=='x'){
        c=get_char();
        return 0;
    } else {
        //rechaza
        rechaza("b g # y x");
        return 0;
    }
}

int K(){
    if (c=='i'){
        c = get_char();
        Q();
        return 0;
    } else {
        // rechaza
        rechaza("i");
        return 0;
    }
}

int Q(){
    if (c==';'){
        return 0;
    } else if (c=='='){
        c = get_char();
        N();
        C();
        return 0;
    } else if (c==','){
        c = get_char();
        K();
        return 0;
    } else {
        //rechaza
        rechaza("; = ,");
        return 0;
    }
}

int N(){
    if (c=='n'){    // prod 22
        c=get_char();
        return 0;
    } else if (c=='r') {    // prod 23
        c=get_char();
        return 0;
    } else if (c=='s'){ // prod 24
        c=get_char();
        return 0;
    } else {
        // rechaza;
        rechaza("n r");
        return 0;
    }
}

int C(){
    if (c==';'){    // prod 25
        return 0;
    } else if (c == ','){   // prod26
        c = get_char();
        K();
        return 0;
    } else {
        //rechaza
        rechaza("; ,");
        return 0;
    }
}

int A(){
    if (c=='i'){
        c = get_char();
        if (c == '='){
            c = get_char();
        } else {
            //rechaza
            rechaza("=");
        }
        APRIMA();
        if (c==';'){
            c=get_char();
        } else {
            //rechaza
            rechaza(";");
        }
        return 0;
    } else {
        //rechaza
        rechaza("i");
        return 0;
    }
}

int APRIMA(){
    if (c=='s'){
        c=get_char();
        return 0;
    } else if (c=='('||c=='i'||c=='n'||c=='r'||c=='['){
        E();
        return 0;
    } else {
        //rechaza
        rechaza("s ( i n r [");
        return 0;
    }
}

int E(){
    if (c=='('||c=='i'||c=='n'||c=='r'||c=='['){
        T();
        EPRIMA();
        return 0;
    } else {
        //rechaza
        rechaza("( i n r [");
        return 0;
    }
}

int EPRIMA(){
    if (c == '+'){
        c = get_char();
        T();
        EPRIMA();
        return 0;
    } else if (c == '-'){
        c = get_char();
        T();
        EPRIMA();
        return 0;
    } else if (c == ')' || c == ';'){
        return 0;
    } else {
        //rechaza
        rechaza("+ - ) ;");
        return 0;
    }
}

int T(){
    if (c=='('||c=='i'||c=='n'||c=='r'||c=='['){
        F();
        TPRIMA();
        return 0;
    } else {
        // rechaza
        rechaza("( i n r [");
        return 0;
    }
}

int TPRIMA(){
    if (c == '*'){
        c = get_char();
        F();
        TPRIMA();
        return 0;
    } else if (c == '/') {
        c = get_char();
        F();
        TPRIMA();
        return 0;
    }  else if (c == '\\') {
        c = get_char();
        F();
        TPRIMA();
        return 0;
    }  else if (c == '%') {
        c = get_char();
        F();
        TPRIMA();
        return 0;
    } else if (c == '^') {
        c = get_char();
        F();
        TPRIMA();
        return 0;
    } else if (c=='+'||c=='-'||c==')'||c==';'){
        return 0;
    } else {
        //rechaza
        rechaza("* / \\ % ^ + - ) ;");
        return 0;
    }
}

int F(){
    if (c == '('){
        c = get_char();
        E();
        if (c==')'){
            c = get_char();
        } else {
            // rechaza
            rechaza(")");
        }
        return 0;
    } else if (c == 'i'){
        c = get_char();
        return 0;
    } else if (c == 'n'){
        c = get_char();
        return 0;
    } else if (c == 'r'){
        c = get_char();
        return 0;
    } else if (c == '['){
        LLAMA();
        return 0;
    } else {
        // rechaza
        rechaza("( i n r [");
        return 0;
    }
}

int R(){
    if (c == 'i'){
        c = get_char();
        RPRIMA();
        V();
        return 0;
    } else if (c == 'n'){
        c = get_char();
        RPRIMA();
        VPRIMA();
        return 0;
    } else if (c == 'r'){
        c = get_char();
        RPRIMA();
        VPRIMA2();
        return 0;
    } else if (c == 's') {
        RPRIMA();
        VPRIMA3();
        return 0;
    } else {
        //rechaza
        rechaza("i n r s");
        return 0;
    }
}

int RPRIMA(){
    if (c=='>'){
        c = get_char();
        return 0;
    } else if (c == '<'){
        c = get_char();
        return 0; 
    } else if (c == 'l'){
        c = get_char();
        return 0; 
    } else if (c == 'e'){
        c = get_char();
        return 0; 
    } else if (c == 'd'){
        c = get_char();
        return 0; 
    } else if (c == 'u'){
        c = get_char();
        return 0; 
    } else {
        //rechaza
        rechaza("> < l e d u");
        return 0;
    }
}

int V(){
    if (c=='i') {
        c = get_char();
        return 0;
    } else if (c == 'n'){
        c = get_char();
        return 0;
    } else if (c == 'r'){
        c = get_char();
        return 0;
    } else if (c == 's'){
        c = get_char();
        return 0;
    } else {
        //rechaza
        rechaza("i n r s");
        return 0;
    }
}

int VPRIMA(){
    if (c == 'n'){
        c = get_char();
        return 0;
    } else if (c == 'i'){
        c = get_char();
        return 0;
    } else {
        //rechaza
        rechaza("n i");
        return 0;
    }
}

int VPRIMA2(){
    if (c == 'r'){
        c = get_char();
        return 0;
    } else if (c == 'i') {
        c = get_char();
        return 0;
    } else {
        // rechaza
        rechaza("r i");
        return 0;
    }
}

int VPRIMA3(){
    if (c == 's') {
        c = get_char();
        return 0;
    } else if (c == 'i') {
        c == get_char();
        return 0;
    } else {
        // rechaza
        rechaza("s i");
        return 0;
    }
}

int P(){
    if (c == 'i'){
        A();
        return 0;
    } else if (c == 'f'){
        I();
        return 0;
    } else if (c == 'h'){
        H();
        return 0;
    } else if (c == 'w'){
        W();
        return 0;
    } else if (c == 'j'){
        J();
        return 0;
    } else if (c == '['){
        LLAMA();
        return 0;
    } else if (c == 'z'){
        DEVUELVE();
        return 0;
    } else if (c == 'c'){
        c = get_char();
        if (c == ';'){
            c = get_char();
        } else {
            //rechaza
            rechaza(";");
        }
        return 0;
    } else {
        //rechaza
        rechaza("i f h w j [ z c");
        return 0;
    }
}

int LISTAP(){
    if (c=='}'||c=='t'||c==':'||c=='q'||c=='a'||c=='o'){
        return 0;
    } else if (c=='c'||c=='i'||c=='f'||c=='h'||c=='w'||c=='j'||c=='['||c=='z'){
        P();
        LISTAP();
        return 0;
    } else {
        //rechaza
        rechaza("} t : q a o c i f h w j [ z");
        return 0;
    }
}

int W(){
    if (c=='w'){
        c = get_char();
        if (c=='('){
            c=get_char();
        } else {
            //rechaza
            rechaza("(");
        }
        R();
        if (c==')'){
            c=get_char();
        } else {
            //rechaza
            rechaza(")");
        }
        if (c=='m'){
            c=get_char();
        } else {
            //rechaza
            rechaza("m");
        }
        if (c=='{'){
            c = get_char();
        } else {
            //rechaza
            rechaza("{");
        }
        LISTAP();
        if (c =='}'){
            c = get_char();
        } else {
            //rechaza
            rechaza("}");
        }
        return 0;
    } else {
        //rechaza
        rechaza("w");
        return 0;
    }
}

int I(){
    if (c=='f'){
        c = get_char();
        if (c=='('){
            c=get_char();
        } else {
            //rechaza
            rechaza("(");
        }
        R();
        if (c==')'){
            c=get_char();
        } else {
            //rechaza
            rechaza(")");
        }
        LISTAP();
        IPRIMA();
        if (c==':'){
            c=get_char();
        } else {
            //rechaza
            rechaza(":");
        }
        return 0;
    } else {
        //rechza
        rechaza("f");
        return 0;
    }
}

int IPRIMA(){
    if (c=='t'){
        c = get_char();
        LISTAP();
        return 0;
    } else if (c == ':'){
        return 0;
    } else {
        //rechaza
        rechaza("t :");
        return 0;
    }
}

int J(){
    if (c=='j'){
        c=get_char();
        if (c=='('){
            c = get_char();
        } else {
            //rechaza
            rechaza("(");
        }
        Y();
        X();
        Z();
        if (c=='{'){
            c=get_char();
        } else {
            //rechaza
            rechaza("{");
        }
        LISTAP();
        if (c=='}'){
            c=get_char();
        } else {
            //rechaza
            rechaza("}");
        }
        return 0;
    } else {
        //rechaza
        rechaza("j");
        return 0;
    }
}

int Y(){
    if (c=='i'){
        c=get_char();
        if (c=='='){
            c=get_char();
        } else {
            //rechaza
            rechaza("=");
        }
        E();
        if (c==';'){
            c=get_char();
        } else {
            //rechaza
            rechaza(";");
        }
        return 0;
    } else if (c == ';'){
        c = get_char();
        return 0;
    } else {
        //rechaza
        rechaza("i ;");
        return 0;
    }
}

int X(){
    if (c=='i'||c=='n'||c=='r'||c=='s'){
        R();
        if (c==';'){
            c=get_char();
        } else {
            //rechaza
            rechaza(";");
        }
        return 0;
    } else if (c == ';'){
        c = get_char();
        return 0;
    } else {
        //rechaza
        rechaza("i n r s ;");
        return 0;
    }
}

int Z(){
    if (c=='i'){
        c = get_char();
        if (c=='='){
            c=get_char();
        } else {
            //rechaza
            rechaza("=");
        }
        E();
        if (c==')'){
            c=get_char();
        } else {
            //rechaza
            rechaza(")");
        }
        return 0;
    } else if (c==')'){
        c = get_char();
        return 0;
    } else {
        //rechaza
        rechaza("i )");
        return 0;
    }
}

int H(){
    if (c == 'h'){
        c = get_char();
        if (c=='('){
            c=get_char();
        } else {
            //rechaza
            rechaza("(");
        }
        if (c=='i'){
            c=get_char();
        } else {
            //rechaza
            rechaza("i");
        }
        if (c==')'){
            c=get_char();
        } else {
            //rechaza
            rechaza(")");
        }
        if (c=='{'){
            c=get_char();
        } else {
            //rechaza
            rechaza("{");
        }
        CPRIMA();
        OPRIMA();
        if (c=='}'){
            c=get_char();
        } else {
            //rechaza
            rechaza("}");
        }
        return 0;
    } else {
        //rechaza
        rechaza("h");
        return 0;
    }
}

int CPRIMA(){
    if (c == 'a'){
        c = get_char();
        if (c=='n'){
            c=get_char();
        } else {
            //rechaza
            rechaza("n");
        }
        if (c==':'){
            c=get_char();
        } else {
            //rechaza
            rechaza(":");
        }
        LISTAP();
        U();
        CPRIMA();
        return 0;
    } else if (c == 'o' || c == '}'){
        return 0;
    } else {
        //rechaza
        rechaza("a o }");
        return 0;
    }
}

int OPRIMA(){
    if (c == 'o'){
        c = get_char();
        if (c==':'){
            c=get_char();
        } else {
            //rechaza
            rechaza(":");
        }
        LISTAP();
        return 0;
    } else if (c == '}'){
        return 0;
    } else {
        //rechaza
        rechaza("o }");
        return 0;
    }
}

int U(){
    if (c == 'q'){
        c = get_char();
        return 0;
    } else if (c == 'a' || c == 'o' || c == '}'){
        return 0;
    } else {
        //rechaza
        rechaza("q a o }");
        return 0;
    }
}

int DEVUELVE(){
    if (c == 'z') {
        c = get_char();
        if (c=='('){
            c=get_char();
        } else {
            //rechaza
            rechaza("(");
        }
        VALOR();
        if (c==')'){
            c=get_char();
        } else {
            //rechaza
            rechaza(")");
        }
        if (c==';'){
            c=get_char();
        } else {
            //rechaza
            rechaza(";");
        }
        return 0;
    } else {
        //rechaza
        rechaza("z");
        return 0;
    }
}

int VALOR(){
    if (c=='i'||c=='n'||c=='r'||c=='s'){
        V();
        return 0;
    } else if (c == ')'){
        return 0;
    } else {
        //rechaza
        rechaza("i n r s )");
        return 0;
    }
}

int LLAMA(){
    if (c == '['){
        c = get_char();
        if (c=='i'){
            c=get_char();
        } else {
            //rechaza
            rechaza("i");
        }
        if (c=='('){
            c=get_char();
        } else {
            //rechaza
            rechaza("(");
        }
        ARG();
        if (c==')'){
            c=get_char();
        } else {
            //rechaza
            rechaza(")");
        }
        if (c==']'){
            c=get_char();
        } else {
            //rechaza
            rechaza("]");
        }
        return 0;
    } else {
        //rechaza
        rechaza("[");
        return 0;
    }
}

int ARG(){
    if (c == ')'){
        return 0;
    } else if (c == 'i'||c=='n'||c=='r'||c=='s'){
        V();
        OTROARG();
        return 0;
    } else {
        //rechaza
        rechaza(") i n r s");
        return 0;
    }
}

int OTROARG(){
    if (c == ','){
        c = get_char();
        V();
        OTROARG();
        return 0;
    } else if (c == ')'){
        return 0;
    } else {
        //rechaza
        rechaza(", )");
        return 0;
    }
}

int main(int argc, char* argv[]){
    yyin = fopen(argv[1], "r"); // Se recibe al archivo de interés con componentes léxicos
    if (yyin!=NULL){
        // Se crean los archivos y se realizan escrituras utiles
        Tokens = fopen("Tokens.txt", "w");  // Archivo para TOKENS
        fprintf(Tokens, "TOKENS\nCLASE\tVALOR\n");
        LiteralesReales = fopen("TablaLiteralesReales.txt", "w");  // Archivo para tabla de literales reales
        fprintf(LiteralesReales, "TABLA DE LITERALES REALES (CLASE 3)\nPOSICION\tDATO\n");
        LiteralesCadenas = fopen("TablaLiteralesCadenas.txt", "w");    // Archivo para tabla de literales cadenas
        fprintf(LiteralesCadenas, "TABLA DE LITERALES CADENAS (CLASE 4)\nPOSICION\tDATO\n");
        Simbolos = fopen("TablaSimbolos.txt", "w");    // Archivo para tabla de simbolos
        fprintf(Simbolos, "TABLAS DE SIMBOLOS (CLASE 1)\nPOSICION\tNOMBRE DEL IDENTIFICADOR\tTIPO\n");
        Errores = fopen("Errores.txt", "w");    // Archivo para errores léxico-sintácticos
        fprintf(Errores, "ERRORES LÉXICOS Y SINTÁCTICOS\n");
        Atomos = fopen("CadenaAtomos.txt", "w");    // Archivo para imprimir a la cadena de átomos
        fprintf(Atomos, "CADENA DE ATOMOS\nINDICE\tATOMOS\n");

        yylex();    // ETAPA: Análisis léxico

        // Se genera la cadena de átomos
        cadena_atomos = generar_cadena_atomos(head_atomos);
        fprintf(Atomos, "\nCadena de atomos lineal: %s\n", cadena_atomos);
        c = get_char(); // Se obtiene al primer caracter de la cadena de átomos para comenzar con el análisis sintáctico recursivo
        PROGRAM();  // ETAPA: Análisis sintáctico recursivo

        // Una vez que concluye la lectura del archivo y se llenan las tablas, se añade la info. en los archivos
        write_tablit(LiteralesReales,head_Real);
        write_tablit(LiteralesCadenas,head_Cadenas);
        write_tabsim(Simbolos,head_tabsim);

        // Se escriben en el archivo de errores léxicos-sintácticos las conclusiones sobre errores
        if (errores_lexicos == 0){
            fprintf(Errores, "El programa fuente no tiene errores léxicos\n");
        }
        if (errores_sintacticos == 0){
            fprintf(Errores, "El programa fuente no tiene errores sintácticos\n");
        }
        if (errores_lexicos + errores_sintacticos == 0){
            fprintf(Errores, "Compilación exitosa, el programa es léxica y sintácticamente correcto\n");
        }

        // Cierra escritura de archivos para guardar archivos en texto
        fclose(Tokens);
        fclose(LiteralesReales);
        fclose(LiteralesCadenas);
        fclose(Simbolos);
        fclose(Errores);
        fclose(Atomos);

        // Lectura de archivos para imprimir contenido en pantalla
        Tokens = fopen("Tokens.txt", "r");  // Archivo para TOKENS
        LiteralesReales = fopen("TablaLiteralesReales.txt", "r");  // Archivo para tabla de literales reales
        LiteralesCadenas = fopen("TablaLiteralesCadenas.txt", "r");    // Archivo para tabla de literales cadenas
        Simbolos = fopen("TablaSimbolos.txt", "r");    // Archivo para tabla de simbolos
        Errores = fopen("Errores.txt", "r");
        Atomos = fopen("CadenaAtomos.txt", "r");
        read_file(Simbolos);
        read_file(LiteralesReales);
        read_file(LiteralesCadenas);
        read_file(Tokens);
        read_file(Atomos);
        read_file(Errores);
        
        // Se cierra la lectura de archivos 
        fclose(Tokens);
        fclose(LiteralesReales);
        fclose(LiteralesCadenas);
        fclose(Simbolos);
        fclose(Errores);
        fclose(Atomos);
        printf("\n");
    } else {
        printf("No existe el programa fuente argumentado o no se argumentó algún archivo.\n");
    }
    return 0;
}
